### ISSUE TITLE
想请教一下

### ISSUE THREAD

**Issue by ckcfcc** [freewind/async_demo#3]
你好，Async初学者，感谢无私的分享经验，现在有点迷惑，whilst里demo中的例子是这样的。

var count1 = 0;
async.whilst(
    function() { return count1 < 3 },
    function(cb) {
        log('1.1 count: ', count1);
        count1++;
        setTimeout(cb, 1000);
    },
    function(err) {
        // 3s have passed
        log('1.1 err: ', err); // -> undefined
    }
);

想请教，这个cb具体是用传递的么？如果需要传递，请问格式是什么呢？能带参数么？
如果第三个函数 err 不为空 是不是循环就跳出了？

**Comment by freewind** [comment]
抱歉，我已经很久不用了，回答不了你的问题

**Comment by freewind** [comment]
可以到这里提，现在已经由其他人在维护了：https://github.com/alsotang/async_demo
